steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f", "Dockerfile.job",
        "-t", "gcr.io/sharplogger/sharp-train-job",
        "."
      ]
images:
  - "gcr.io/sharplogger/sharp-train-job"
