FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8080
CMD sh -c "uvicorn sharp_trigger_service:app --host 0.0.0.0 --port $PORT"

