FROM python:python:3.10-alpine

WORKDIR /app


# Install build dependencies (needed for many Python packages on Alpine)
RUN apk add --no-cache build-base gcc musl-dev libffi-dev

COPY requirements.txt .
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=8080

CMD ["uvicorn", "sharp_trigger_service:app", "--host", "0.0.0.0", "--port", "8080"]

